[package]
name = "sauron-component-macro"
version = "0.50.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.95", features = ["full"] }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "1.1.3"
