[package]
name = "sauron-md"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sauron = { path = "../../", version = "0.24.0" }
sauron-parse = { path = "../sauron-parse", version = "0.1.0" }
pulldown-cmark = { version = "0.7.0"}
