[package]
name = "sauron"
version = "0.10.1"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "An html library for building client side webapps"
repository = "https://github.com/ivanceras/sauron"
documentation = "https://docs.rs/sauron"
readme = "README.md"
keywords = ["html", "dom", "web"]
edition = "2018"

[dependencies]
js-sys = "0.3.19"
sauron_vdom = "0.10.1-alpha.0"
wasm-bindgen = "0.2.45"
lazy_static = "1.3.0"
pulldown-cmark = { version = "0.5.1", optional = true }

[dependencies.web-sys]
version = "0.3.22"
features = [
    "Comment",
    "console",
    "Document",
    "Element",
    "Event",
    "HtmlElement",
    "EventTarget",
    "KeyboardEvent",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "MouseEvent",
    "Node",
    "NodeList",
    "Text",
    "CharacterData",
    "Performance",
    "Window",
    "History",
    "Response",
]


[features]
default = ["with-markdown"]
measure = []
with-markdown = ["pulldown-cmark"]
no_request_animation_frame = [] # disable request animation frame
with-serde = ["sauron_vdom/serde"]

[dev-dependencies]
wasm-bindgen-test = "0.2.45"
console_error_panic_hook = "0.1.6"

[dev-dependencies.web-sys]
version = "0.3.22"
features = [
    "DomTokenList",
    "HtmlInputElement",
    "Event",
    "MouseEvent",
    "InputEvent",
    "console",
    "Performance",
]

[workspace]
members = [
    "crates/sauron_vdom",
    "examples/minimal",
    "examples/fetch_data",
    "examples/interactive/client",
    "examples/todomvc",
    "examples/todomvc_using_array",
    "examples/window_tab_rows",
]



[profile.release]
# Warning: Do not use 'z' it removes a lot of things including the closures
opt-level = 's'
lto = true

[replace]
"sauron_vdom:0.10.1-alpha.0" = { path = "crates/sauron_vdom" }
