[package]
name = "sauron"
version = "0.50.5"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A versatile web framework and library for building client-side and/or server-side web applications"
repository = "https://github.com/ivanceras/sauron"
documentation = "https://docs.rs/sauron"
readme = "README.md"
keywords = ["html", "dom", "web"]
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
sauron-core = { version = "0.50", path = "crates/sauron-core", default-features = false }
sauron-node-macro = { version = "0.50", path = "crates/sauron-node-macro", optional = true }
sauron-component-macro = { version = "0.50", path = "crates/sauron-component-macro"}
cfg-if = "0.1"

[features]
default = ["with-dom", "with-node-macro"]
with-dom = ["sauron-core/with-dom"]
with-lookup = ["sauron-core/with-lookup"]

# shows telemetry such as duration it took to update the dom
with-measure = ["sauron-core/with-measure"]
# log debug patches
with-debug = ["sauron-core/with-debug"]

# lets you use node! macro to write html like code in the view
with-node-macro = ["sauron-node-macro"]


[dev-dependencies]
console_error_panic_hook = "0.1"
console_log = "0.2"
log = "0.4"
wasm-bindgen-test = "0.3"
regex = "1"

[dev-dependencies.web-sys]
version = "0.3"
features = [
    "DomTokenList",
    "HtmlInputElement",
    "Event",
    "MouseEvent",
    "InputEvent",
    "console",
    "Performance",
]


[workspace]
members = [
    "crates/*",
    "examples/*",
]

# progressive-rendering example has its own workspace
exclude = [
    "examples/custom-element", 
    "examples/progressive-rendering"
]



[patch.crates-io]
#mt-dom = { git = "https://github.com/ivanceras/mt-dom.git", branch = "master" }
#mt-dom = { path = "../mt-dom" }
#jss = { git = "https://github.com/ivanceras/jss.git", branch = "master" }
#jss = { path = "../jss" }
