[package]
name = "sauron-core"
version = "0.31.2"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "An html library for building client side webapps"
repository = "https://github.com/ivanceras/sauron"
documentation = "https://docs.rs/sauron-core"
readme = "../../README.md"
keywords = ["html", "dom", "web"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
lazy_static = "1.3.0"
log = "0.4"
cfg-if = "0.1"
thiserror = "1.0"
doc-comment = "0.3"
mt-dom = { version = "0.4", path = "../../../mt-dom" }
console_log = { version = "0.2", optional = true, features = ["color"] }
serde_json = { version = "1", features = ["preserve_order"] }

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
    "AnimationEvent",
    "Comment",
    "console",
    "Document",
    "Element",
    "Event",
    "HtmlElement",
    "EventTarget",
    "KeyboardEvent",
    "HashChangeEvent",
    "InputEvent",
    "HtmlCollection",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "MouseEvent",
    "Node",
    "NodeList",
    "Text",
    "TransitionEvent",
    "CharacterData",
    "Performance",
    "Window",
    "History",
    "Response",
	"Location",
	"ScrollToOptions",
]


[features]
default = ["with-dom", "with-request-animation-frame"]
with-parser = [] #enumerates html tags and attributes
with-measure = ["mt-dom/with-measure"]
with-request-animation-frame = [] # enable the use of request-animation-frame in calling dispatch
with-dom = ["wasm-bindgen", "js-sys", "web-sys", "console_log"]

[dev-dependencies]
wasm-bindgen-test = "0.3"
console_error_panic_hook = "0.1"
console_log = "0.2"

[dev-dependencies.web-sys]
version = "0.3"
features = [
    "DomTokenList",
    "HtmlInputElement",
    "Event",
    "MouseEvent",
    "InputEvent",
    "console",
    "Performance",
]

[dev-dependencies.criterion]
version = "0.3"

[[bench]]
name = "nodes_benchmark"
harness = false

