[package]
name = "custom_widget"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sauron = { path = "../../" }
log = "0.4"
console_log = "0.2"
console_error_panic_hook = "0.1"
