[package]
name = "interactive"
version = "0.1.0"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1"
js-sys = "0.3"
sauron = { path = "../../../" }
log = "0.4"
console_log = "0.1"
wee_alloc = { version = "0.4", optional = true }

[dependencies.wasm-bindgen]
version = "0.2"


